Try a fix with logs

diff --git a/watcher b/watcher
--- a/watcher
+++ b/watcher
@@ -51,8 +51,8 @@ do
   if [ ! -d "'$filepath'" ] && [ ! $event = 'CREATE' ]
   then
     source activate watcher_env # for activating the right conda python env
-    conda info --envs >>$LOGFILE 2&>1
-    sudo tsp python parser_controller.py "'$filepath'"  && (./log $0 "START : sudo tsp python parser_controller.py $filepath ") || (./log $0 "ERROR while launchin sudo tsp python...")
+    ./log $0 "conda info --envs"
+    # sudo tsp python parser_controller.py "'$filepath'"  && (./log $0 "START : sudo tsp python parser_controller.py $filepath ") || (./log $0 "ERROR while launching sudo tsp python...")
   else
     ./log $0 "PASS : no planned action for a directory or on CREATE event (waiting for CLOSE event)"
   fi
