Try a fix with logs

diff --git a/watcher b/watcher
--- a/watcher
+++ b/watcher
@@ -50,10 +50,9 @@ do
   ./log $0 "On $date $time, Event : $event $filepath"
   if [ ! -d "'$filepath'" ] && [ ! $event = 'CREATE' ]
   then
-    source activate watcher_env # for activating the right conda python env
-    ./log $0 "Path i s:   $(echo $PATH)"
-    ./log $0 "Conda activated env is : $(conda info --envs | grep '*')"
-    # sudo tsp python parser_controller.py "'$filepath'"  && (./log $0 "START : sudo tsp python parser_controller.py $filepath ") || (./log $0 "ERROR while launching sudo tsp python...")
+    sudo PATH=$PATH conda activate watcher_env # for activating the right conda python env
+    sudo PATH=$PATH ./log $0 "Path is: $(echo $PATH)"
+    sudo PATH=$PATH tsp python parser_controller.py "'$filepath'"  && (./log $0 "START : sudo tsp python parser_controller.py $filepath ") || (./log $0 "ERROR while launching sudo tsp python...")
   else
     ./log $0 "PASS : no planned action for a directory or on CREATE event (waiting for CLOSE event)"
   fi
